name: Build and Push Docker Image to ECR

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build and tag Docker image
        run: |
          docker build -t yahpa-website:latest .
          docker tag yahpa-website:latest 557690602076.dkr.ecr.us-east-2.amazonaws.com/yahpa-website:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 557690602076.dkr.ecr.us-east-2.amazonaws.com/yahpa-website:latest