# filename: .github/workflows/test.yml
name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js application
        run: yarn build

      - name: Start Next.js application
        run: yarn start &
        env:
          CYPRESS_BASE_URL: http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}